name: CMake-action

#trigger
on:
  push:
   branches: [dev]
  workflow_dispatch:

jobs:
    #job name "build debug"
  build-debug:

    env:
      BUILD_TYPE: Debug

    #version Os
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

