name: CMake-action v13

#trigger
on:
  push:
   branches: [dev]
  workflow_dispatch:

jobs:
    #job name "build debug"
  build-debug:

    env:
      BUILD_TYPE: Debug
      GITHUB_BUILD: on

    #version Os
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [macOS-latest, ubuntu-22.04]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Submodules
        run: git submodule init && git submodule update

      - name: Mount vcpkg cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/vcpkg/archives"
          key: vcpkg-linux

      - name: Install libcurl
        run: vcpkg install curl

#      - name: Install gpiod
#        if: ${{ matrix.os == 'ubuntu-22.04' }}
#        run: apt-get install -y gpiod libgpiod-dev

      - name: Configure CMake MacOsx
        if: ${{ matrix.os == 'macOS-latest' }}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Configure CMake 'ubuntu-22.04
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGITHUB_BUILD=ON

      - name: Build task
        if: ${{ matrix.os == 'macOS-latest' }}
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
